[FEAT] 반려동물 등록 api 생성
KAU-SMART-PETS/Capstone_BE pull request #6
Opened 2024-05-07 18:14 UTC by jun23314

# 😁 Issue Link
- close #3 

# 😆 To Reviewers

# 😚 Reference

- 

# 📌 PR 진행 시 이러한 점들을 참고해 주세요
* Reviewer 분들은 코드 리뷰 시 좋은 코드의 방향을 제시하되, **코드 수정을 강제하지 말아 주세요.**
* Reviewer 분들은 좋은 코드를 발견한 경우, **칭찬과 격려**를 아끼지 말아 주세요.
* Review는 특수한 케이스가 아니면 Reviewer로 지정된 시점 기준으로 **7일 이내에 진행**해 주세요.
* Comment 작성 시 Prefix로 P1, P2, P3 를 적어 주시면 Assignee가 보다 명확하게 Comment에 대해 대응할 수 있어요
  * P1 : **꼭 반영해 주세요** (Request Changes) - 이슈가 발생하거나 취약점이 발견되는 케이스 등
  * P2 : 반영을 **적극적으로 고려**해 주시면 좋을 것 같아요 (Comment)
  * P3 : 이런 방법도 있을 것 같아요~ 등의 **사소한 의견**입니다 (Chore)

2024-05-07 22:57 UTC, 70825 requested changes
안녕하세요~ 아래 사항 확인 부탁드립니다~

- 코드 컨벤션: 어노테이션은 길이 순서대로 작성
- `Primitive Type`과 `Non Primitive Type`이 혼용되어 있어서 통일하거나 따로 코멘트 남겨주시면 좋을 것 같습니다
- 사용하지 않는 import 문도 있어서 제거하면 좋을 것 같습니다

P1, P2, P3 기준은 아래로 사용했습니다.
- P1: 반영해야하는 내용
- P2: 더 의견을 나눠야할 내용
- P3: 제가 아예 모르는 내용이라 질문한 내용

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +    }
P2: `PetRestController`는 무조건 `200 OK`를 반환하는 것인가요? `201 Created`도 있고, `URL + PostMapping + 200 OK`로 반려동물 정보를 저장에 성공 했다는걸 알 수 있는데, `200 OK` 선택 이유와 body에 내용을 성공했다는 메시지를 추가하는 이유도 궁금합니다.

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +@RequestMapping("v1/pet")
P2: 프론트엔드와 백엔드 구분지어서 프로젝트를 진행하기 때문에 백엔드로 접속하는 URL의 접두사는 통일된 내용으로 하는게 좋아보입니다. (ex. `/api/v1/pet`)

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +    public ResponseDTO<String> createSido(PetRegistRequest petRegistRequest) {
P2: `ResponseEntity`를 사용하면 따로 `ResponseDTO` 파일을 추가할 필요 없이 아래처럼 만들 수 있습니다.

```java
@PostMapping("/regist")
public ResponseEntity<String> createSido(PetRegistRequest petRegistRequest) {
    petService.registPet(petRegistRequest);
    return ResponseEntity.ok()
        .body("성공적으로 반려동물 정보를 저장하였습니다.");
}
```

상태코드 코드 통일성도 생각한다면 아래처럼 만들 수 있습니다


```java
@PostMapping("/regist")
public ResponseEntity<String> createSido(PetRegistRequest petRegistRequest) {
    petService.registPet(petRegistRequest);
    return ResponseEntity.status(HttpStatus.OK)
        .body("성공적으로 반려동물 정보를 저장하였습니다.");
}
```

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +    public ResponseDTO<String> createSido(PetRegistRequest petRegistRequest) {
P1: 메서드 이름도 수정해야 할 것 같습니다.

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java
> +    }
P3: `Request`에 `@Builder`가 적용된 이유가 있는지 궁금합니다

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/service/PetService.java
> +public class PetService {
1) P3: `@Slf4j`가 추가된 이유가 있을까요?

2) P1: `registPet`은 데이터베이스에 데이터를 추가하는 것이라 `@Transactional` 추가가 필요해 보입니다. JPA를 사용하는 것이니 `@Transactional(readOnly=True)`도 찾아보시면 좋을 것 같아요

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/global/common/BaseEntity.java
> +    @Setter
P3: `@Setter`가 추가된 이유가 있는지 궁금합니다

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/global/common/BaseEntity.java
> +    }
P3: hard delete 대신 soft delete를 하는 이유가 따로 있는지 궁금합니다

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/global/common/Gender.java
> +    Gender(int value) {this.value = value;}
P1: 이거는 아래처럼 정리부탁드립니다. `PetType`도 반영 부탁드려요

```suggestion
    MALE(1), FEMALE(2);
    
    private final Integer value;

    Gender(int value) {
        this.value = value;
    }
```

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/global/common/Gender.java
> +    }
P2: 이거는 추가한 이유가 있을까요??

2024-05-07 22:57 UTC, 70825 commented on src/main/java/com/kau/capstone/global/common/Gender.java
> +            throw new IllegalArgumentException("유효하지 않은 성별입니다.");
P1: 여기는 어차피 `if` - `else if`문을 통과하면 에러를 반환하기 때문에 굳이 `else`를 명시적으로 할 필요는 없어보입니다.
`PetType`도 마찬가지입니다.

```suggestion
        if(value == 1) return MALE;
        else if(value == 2) return FEMALE;

        throw new IllegalArgumentException("유효하지 않은 성별입니다.");
```

2024-05-08 03:56 UTC, jun23314 commented on src/main/java/com/kau/capstone/domain/pet/service/PetService.java
> +public class PetService {
1. 로그를 많이 사용하기 때문에 저는 서비스 클래스를 만들 때 미리 어노테이션을 추가해놓는 편입니다!
2. Transactional은 repository.find 같은 쿼리문을 여러개 사용하는 경우에 필수적인 것이라고 생각하여 사용하지 않았습니다. 말씀해주신 대로 알아보니 추가하는게 좋을 것 같아서 추가해두겠습니다!

2024-05-08 04:14 UTC, jun23314 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +    public ResponseDTO<String> createSido(PetRegistRequest petRegistRequest) {
1. 메서드 이름은 수정해두겠습니다!
2. ResponseDTO같은 경우에는, 말씀해주신 방법도 알고 있지만 저는 따로 파일을 만들어두고 사용하는 방식이 편해서 이 방식을 사용해왔습니다. 혹시 이게 불편하시다면 두가지 방법의 장단점을 생각해보는 것도 방법이겠네요:)

2024-05-08 04:17 UTC, jun23314 commented on src/main/java/com/kau/capstone/global/common/Gender.java
> +    Gender(int value) {this.value = value;}
1번으로 정리해두겠습니다~

2024-05-08 04:19 UTC, jun23314 commented on src/main/java/com/kau/capstone/global/common/Gender.java
> +    }
음.. 생각해보니 사용할 일이 없을 것 같네요.. 삭제해두겠습니다!

2024-05-08 04:21 UTC, jun23314 commented on src/main/java/com/kau/capstone/global/common/Gender.java
> +            throw new IllegalArgumentException("유효하지 않은 성별입니다.");
제 개인적인 의견이지만, 저는 if, else if, else를 모두 명시하는게 코드 가독성이 좋다고 생각합니다.. 그래서 else를 넣어두었는데, 혹시 어떻게 생각하시나요?

2024-05-08 04:25 UTC, jun23314 commented on src/main/java/com/kau/capstone/global/common/BaseEntity.java
> +    }
데이터를 삭제할 때, 한번에 삭제하는 것 보다 삭제되었다는 표시만 해두고 일정 기간 뒤에 삭제하는 것이 좋다고 공부하여서 soft delete를 사용하였습니다!
이 부분도 어떤게 더 좋을지 애기해보면 좋을 것 같습니다:)

2024-05-08 04:30 UTC, jun23314 commented on src/main/java/com/kau/capstone/domain/pet/dto/request/PetRegistRequest.java
> +    }
request가 record 형식입니다!
현재 제가 이해하고 있는 로직으로는 RequestDto를 생성하면 생성자를 통해 record가 생성됩니다. Builder가 적용된 이유는.. 사실 Builder 없이 해봤는데 안돼서...ㅎㅎ 이부분은 저도 조금 자세하게 찾아보겠습니다

2024-05-08 04:30 UTC, jun23314 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +@RequestMapping("v1/pet")
넵 변경해두겠습니다

2024-05-08 04:41 UTC, jun23314 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +    }
201Created를 사용하는 것도 좋은 방법이겠네요!
제가 200 OK를 사용한 특별한 이유는 없습니다. Body에 메시지를 추가한 것은, 코드를 보는 입장에서 어떤 정보를 저장하였는지 명시해두기 위함입니다. 그리고 저장에 성공했으니 200OK를 사용하면 된다고 생각하였습니다.

2024-05-08 06:00 UTC, 70825 commented on src/main/java/com/kau/capstone/global/common/Gender.java
> +            throw new IllegalArgumentException("유효하지 않은 성별입니다.");
저는 사실 프로젝트할 때 [객체지향 생활체조 원칙](https://catsbi.oopy.io/bf003ff6-2912-4714-8ac2-44eeb7becc93)을 최대한 적용해와서 else는 진짜 어쩔 수 없는 경우에만 쓴 기억 밖에 없어가지구요
코드 스타일이랑 많이 다르시면 else문은 그대로 두시면 될 것 같습니다

2024-05-08 06:06 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/service/PetService.java
> +public class PetService {
1. 아하 이해했습니다. 저는 필요하기 전까지 아예 코드를 추가하지 않는 편이라서 아직 사용되는 곳이 없길래 궁금했습니다
2. 넵넵 어차피 모든 Service 파일에 `@Transactional`이 추가될 확률이 높아서 나중에 컨벤션으로 이야기해보면 좋을 것 같습니다.

2024-05-08 06:12 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +    public ResponseDTO<String> createSido(PetRegistRequest petRegistRequest) {
저 2번 코멘트가 잘 이해가 안가는데 상태코드를 사용할 수 없는 구조로 보여서 이거는 나중에 추가되는 건가요?
`ResponseEntity<ResponseDTO>`로 주로 사용해왔는데, `ResponseDTO`만 사용하는건 처음봐서요

2024-05-08 06:27 UTC, jun23314 commented on src/main/java/com/kau/capstone/global/common/Gender.java
> +            throw new IllegalArgumentException("유효하지 않은 성별입니다.");
아하,, 그렇군요. 이해했습니다
추천해주신대로 else 예약어 제외하여 코드 수정해두었습니다!

2024-05-08 06:28 UTC, jun23314 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +    public ResponseDTO<String> createSido(PetRegistRequest petRegistRequest) {
아 제가 코드에 빠트린 부분이 있었네요,
어떤 부분을 말씀하시는건지 이해했습니다.
상태코드는 컨트롤러의 어노테이션에 명시해둡니다!
@ResponseStatus(HttpStatus.OK) 이런식으로 사용하고 있습니다.

2024-05-08 06:55 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +    public ResponseDTO<String> createSido(PetRegistRequest petRegistRequest) {
그러면 Header에 값을 추가할 때는 어떻게 사용하시나요?? 예를 들어서 나중에 생성이나 삭제, 로그인하는 과정에서 Location 헤더가 필요한데, 이때는 결국엔 `ResponseEntity`로 감쌀 수 밖에 없는 것 같아서요

---

뭔가 많이 질문해서 죄송해요 😭 막 클린코드에 집착하는건 아니고 1년 동안 계속 코드를 봐야하기도 하고, 초반 코드가 거의 확정적인 컨벤션으로 자리잡으니까 이왕이면 다른 분이 작성한 코드도 서로 이해하기 편하게 규칙성 있는 코드가 좋아서요 ㅠㅠ 양심이 많이 찔려서 먼저 선변명해봅니다.. 아니면 회의에서 이야기 해보는게 좋을 것 같아요

2024-05-08 07:03 UTC, jun23314 commented on src/main/java/com/kau/capstone/domain/pet/controller/PetRestController.java
> +    public ResponseDTO<String> createSido(PetRegistRequest petRegistRequest) {
헙 아니에요!
질문해주시는 내용 확인하면서 저도 당연하게 생각하고 넘어갔던 부분들을 한번 더 생각해볼 수 있어서 좋아요!
그리고 코드 컨벤션은 중간에 바꾸기 힘드니까 처음에 맞추고 넘어가는게 좋은 것 같아요! 😄 

ResponseDTO 형식은 저도 이번에 다른 프로젝트 진행하면서 새롭게 사용하게 된 방식이라, 정확하게 답변을 드릴 수 없는 점 죄송합니다..
사실 저는 프로젝트 진행하면서 헤더에 값을 추가해본 적이 없어서 다빈님께서 말씀하신 케이스는 생각해본 적이 없는.. 상황입니다.

Response Entity를 사용한다면, 헤더에 값을 어떻게 추가하는지에 대한 예시 코드를 알려주실 수 있을까요?
저도 이 부분은 조금 더 알아보겠습니다!

2024-05-10 01:12 UTC, 70825 requested changes
한 번 더 꼼꼼하게 살펴봤는데, 위에 코멘트랑 현재 코멘트 확인해주시고 반영할거 반영하면 머지해도 될 것 같습니다~

2024-05-10 01:12 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/entity/Pet.java
> +    @Builder
P2: 클래스에 적용되는 어노테이션들은 다 class 선언 위에 붙어 있어서 `@Builder`도 마찬가지로 class 위에 붙이는게 좋아보입니다

2024-05-10 01:12 UTC, 70825 commented on src/main/java/com/kau/capstone/domain/pet/entity/Pet.java
> +    public Pet(Long id, String name, PetType petType, Gender gender, float weight, Integer age,
float만 primitive type으로 해둔 이유가 있을까요?

2024-05-10 01:12 UTC, 70825 commented on src/main/java/com/kau/capstone/global/common/Gender.java
> +    // 정수를 ENUM으로 변환하는 메서드
P2: 현재 메서드는 다들 알고 있는 메서드라 삭제해도 될 것 같아요

2024-05-10 01:12 UTC, 70825 commented on src/main/java/com/kau/capstone/global/common/Gender.java
> +            throw new IllegalArgumentException("유효하지 않은 성별입니다.");
P2: 이 에러는 커스텀 예외를 만들어두면 좋아보여요
P1: 이전 코멘트에서 else문은 삭제하기로 했어서 PetType처럼 수정하시면 될 것 같습니다

2024-05-10 01:12 UTC, 70825 commented on src/main/java/com/kau/capstone/global/common/PetType.java
> +    // 정수를 ENUM으로 변환하는 메서드
P2: 여기도 삭제해도 문제 없어보입니다

2024-05-14 06:15 UTC, jun23314 commented on src/main/java/com/kau/capstone/domain/pet/entity/Pet.java
> +    public Pet(Long id, String name, PetType petType, Gender gender, float weight, Integer age,
nullable false 값이라 원시타입 사용했습니다!

2024-05-21 10:55 UTC, 70825 approved these changes
고생하셨습니다 ~

2024-05-23 09:34 UTC, merged